"""
handles parsing commands from command bar
"""
import asyncio
import uuid
from typing import Optional

from fastapi.encoders import jsonable_encoder

from app.ai.intent_classsifier import IntentSimilarityModel
from app.schemas.base_command import BaseCommand, MatchResult, CommandResult
from app.ai.llm import Extractor, GeneralLLM, TOOL_SYSTEM_PROMPT, build_tool_index, build_tools, tool_status_text

import json
import logging

logger = logging.getLogger(__name__)
MAX_TOOL_ROUNDS = 10
WRITE_CONFIRM_TIMEOUT = 120.0  # seconds to wait for the user to confirm a write


# ---------------------------------------------------------------------------
# write-confirmation registry
# ---------------------------------------------------------------------------

class _PendingWrite:
    """Holds the asyncio.Event a streaming generator awaits until the user
    confirms or declines a write action via POST /command/confirm-write."""
    __slots__ = ("event", "confirmed")

    def __init__(self):
        self.event = asyncio.Event()
        self.confirmed = False


_pending_writes: dict[str, _PendingWrite] = {}


def resolve_write(token: str, confirmed: bool) -> bool:
    """Resolve a pending write confirmation.  Returns True if the token was
    valid and the event was set; False if the token was unknown (expired or
    already consumed)."""
    entry = _pending_writes.pop(token, None)
    if entry is None:
        return False
    entry.confirmed = confirmed
    entry.event.set()
    return True


class CommandRouter:
    def __init__(self, intent_classifier: IntentSimilarityModel, llm_extractor: Extractor, general_llm: GeneralLLM, classifier_confidence_threshold: float = 0.7):
        self.plugins: list[BaseCommand] = []
        self.classifier = intent_classifier
        self.llm_extractor = llm_extractor
        self.general_llm = general_llm
        self.confidence_threshold = classifier_confidence_threshold
        self._built = False
        self._tools: list[dict] = []
        self._tool_index: dict = {}

    def register_plugin(self, plugin: BaseCommand) -> None:
        if not isinstance(plugin, BaseCommand):
            return
        self.plugins.append(plugin)
        self._built = False

    def _ensure_built(self):
        if not self._built:
            self.classifier.build(self.plugins)
            self._tools = build_tools(self.plugins, intent_types=("read", "write"))
            self._tool_index = build_tool_index(self.plugins, intent_types=("read", "write"))
            self._built = True

    async def _execute_tool(self, name: str, args: dict, raw: str) -> str:
        entry = self._tool_index.get(name)
        if not entry:
            return f"Error: unknown tool '{name}'"
        plugin, spec = entry
        try:
            result = await plugin.handle(spec.name, args, raw)
        except Exception as e:
            logger.error("tool %s raised: %s", name, e)
            return f"Error executing {name}: {str(e)}"
        if not result.success:
            return f"Error: {result.response_text}"
        payload = json.dumps(jsonable_encoder(result.data)) if result.data else ""
        return "\n".join(part for part in (result.response_text, payload) if part)
        
    async def _llm_stream(self, raw: str):
        messages = [
            {"role": "system", "content": TOOL_SYSTEM_PROMPT},
            {"role": "user", "content": raw},
        ]

        for _ in range(MAX_TOOL_ROUNDS):
            tool_calls = {}
            content_parts = []

            async for chunk in self.general_llm.chat_stream(
                messages=messages,
                tools=self._tools,
                temperature=0.3,
            ):
                if not chunk.choices:
                    # provider may emit a trailing usage/keep-alive chunk with
                    # empty choices — nothing to consume, just skip it.
                    continue
                delta = chunk.choices[0].delta

                # Normal text generated by the model
                if delta.content:
                    content_parts.append(delta.content)
                    yield {
                        "type": "text",
                        "content": delta.content,
                    }

                # Tool calls arrive incrementally while streaming
                if delta.tool_calls:
                    for tc in delta.tool_calls:
                        index = tc.index

                        if index not in tool_calls:
                            tool_calls[index] = {
                                "id": "",
                                "name": "",
                                "arguments": "",
                            }

                        if tc.id:
                            tool_calls[index]["id"] += tc.id

                        if tc.function:
                            if tc.function.name:
                                tool_calls[index]["name"] += tc.function.name

                            if tc.function.arguments:
                                tool_calls[index]["arguments"] += tc.function.arguments

            # No tool calls means the model has finished answering.
            if not tool_calls:
                return

            # Reconstruct the assistant's tool-call message.
            assistant_tool_calls = []

            for call in tool_calls.values():
                assistant_tool_calls.append({
                    "id": call["id"],
                    "type": "function",
                    "function": {
                        "name": call["name"],
                        "arguments": call["arguments"],
                    },
                })

            messages.append({
                "role": "assistant",
                "content": "".join(content_parts) or None,
                "tool_calls": assistant_tool_calls,
            })

            # Execute every requested tool.
            for call in tool_calls.values():
                try:
                    args = json.loads(call["arguments"])
                except json.JSONDecodeError:
                    result = "Error: model produced invalid tool arguments."
                else:
                    spec_entry = self._tool_index.get(call["name"])
                    spec = spec_entry[1] if spec_entry else None

                    if spec is not None and spec.type == "write":
                        # --- write: pause the stream and wait for user
                        # confirmation via POST /command/confirm-write ---
                        token = uuid.uuid4().hex
                        entry = _PendingWrite()
                        _pending_writes[token] = entry

                        yield {
                            "type": "confirm_write",
                            "token": token,
                            "tool": call["name"],
                            "title": spec.command_name,
                            "args": args,
                        }

                        try:
                            await asyncio.wait_for(
                                entry.event.wait(), timeout=WRITE_CONFIRM_TIMEOUT
                            )
                            confirmed = entry.confirmed
                        except asyncio.TimeoutError:
                            confirmed = False
                        finally:
                            _pending_writes.pop(token, None)

                        if confirmed:
                            result = await self._execute_tool(
                                call["name"], args, raw
                            )
                        else:
                            result = (
                                "The user declined this action. "
                                "Do not claim that it was performed."
                            )
                    else:
                        # --- read: execute immediately (unchanged) ---
                        if spec_entry:
                            plugin, spec = spec_entry

                            # Let the frontend know what is happening.
                            yield {
                                "type": "tool_start",
                                "tool": call["name"],
                                "plugin": plugin.name,
                                "status": tool_status_text(spec),
                            }

                        result = await self._execute_tool(
                            call["name"],
                            args,
                            raw,
                        )

                messages.append({
                    "role": "tool",
                    "tool_call_id": call["id"],
                    "content": result,
                })

                yield {
                    "type": "tool_end",
                    "tool": call["name"],
                    "result": result,
                }

        # Safety fallback if the model keeps requesting tools.
        yield {
            "type": "text",
            "content": "I couldn't complete the request because too many tool calls were required.",
        }

    async def _run_llm_stream(self, raw: str):
        """Stream the general LLM (with tool calling) to completion, then yield
        the terminal result.  Shared by the low-confidence fallback and the
        explicit "llm" command mode."""
        try:
            answer_parts = []
            async for event in self._llm_stream(raw):
                if event["type"] == "text":
                    answer_parts.append(event["content"])
                yield event

            yield {"type": "result", "result": CommandResult(
                success=True,
                action='LLM_RESPONSE',
                response_text="".join(answer_parts),
                data={},
            )}
        except Exception as e:
            yield {"type": "result", "result": CommandResult(
                success=False,
                action='LLM_ERROR',
                response_text=f"Error in LLM response: {str(e)}",
                data={},
            )}

    async def process_stream(self, raw: str, mode: str = "normal"):
        if not raw or not raw.strip():
            yield {"type": "result", "result": CommandResult(success=False, action='EMPTY', response_text="Nothing to process", data={})}
            return

        raw = raw.strip()
        self._ensure_built()

        if mode == "llm":
            # Explicit "straight to LLM" mode — skip the classifier entirely.
            async for event in self._run_llm_stream(raw):
                yield event
            return

        match = await self.classifier.classify(raw)

        if not match:
            yield {"type": "result", "result": CommandResult(success=False, action='NO_MATCH', response_text="No matching command found", data={})}
            return

        if match.confidence < self.confidence_threshold:
            # fall through to llm
            async for event in self._run_llm_stream(raw):
                yield event
            return

        plugin = self._get_plugin(match.plugin)
        if not plugin:
            yield {"type": "result", "result": CommandResult(success=False, action='PLUGIN_NOT_FOUND', response_text=f"Plugin {match.plugin} not found", data={})}
            return

        result = await self._run_intent(plugin, match.intent, raw)
        yield {"type": "result", "result": result}

        

    async def process(self, raw: str) -> CommandResult:
        """
        takes in raw command string, called by api
        """
        if not raw or not raw.strip():
            return CommandResult(success=False, action='EMPTY', response_text="Nothing to process", data={})

        raw = raw.strip()
        self._ensure_built()

        match = await self.classifier.classify(raw)

        if not match:
            return CommandResult(success=False, action='NO_MATCH', response_text="No matching command found", data={})

        if match.confidence < self.confidence_threshold:
            if match.confidence >= 0.5:
                # don't extract slots yet - just ask the user to confirm the intent.
                # send back everything needed to resume without re-classifying.
                return CommandResult(
                    success=True,
                    action='NEEDS_CONFIRMATION',
                    response_text=f"{match.intent_name}?",
                    data={
                        "intent": match.intent,
                        "plugin": match.plugin,
                        "confidence": match.confidence,
                        "raw": raw,
                    }
                )
            else:
                # fall through to llm general response
                try:
                    answer = await asyncio.to_thread(self.general_llm.ask, raw)
                    return CommandResult(
                        success=True,
                        action='LLM_RESPONSE',
                        response_text=answer,
                        data={},
                    )
                except Exception as e:
                    return CommandResult(
                        success=False,
                        action='LLM_ERROR',
                        response_text=f"Error in LLM response: {str(e)}",
                        data={},
                    )

        plugin = self._get_plugin(match.plugin)
        if not plugin:
            return CommandResult(success=False, action='PLUGIN_NOT_FOUND', response_text=f"Plugin {match.plugin} not found", data={})

        return await self._run_intent(plugin, match.intent, raw)

    async def confirm(self, intent: str, plugin_name: str, raw: str) -> CommandResult:
        """
        resumes processing after the user confirms a NEEDS_CONFIRMATION prompt.
        skips classification entirely - the frontend just echoes back what
        process() sent it in `data` (intent, plugin, raw).
        """
        plugin = self._get_plugin(plugin_name)
        if not plugin:
            return CommandResult(success=False, action='PLUGIN_NOT_FOUND', response_text=f"Plugin {plugin_name} not found", data={})

        # guard against a confirm() call for an intent this plugin doesn't
        # actually own (defensive - shouldn't happen if frontend just echoes data back)
        if not plugin.get_intent(intent):
            return CommandResult(success=False, action='INTENT_NOT_FOUND', response_text=f"Intent {intent} not found on {plugin_name}", data={})

        return await self._run_intent(plugin, intent, raw)

    async def _run_intent(self, plugin: BaseCommand, intent: str, raw: str) -> CommandResult:
        """
        shared path: extract slots (if needed) then hand off to the plugin.
        used by both process() (high-confidence match) and confirm() (post-confirmation).
        """
        try:
            extracted = await self._extract_slots(plugin, intent, raw)
        except Exception as e:
            return CommandResult(success=False, action='EXTRACTION_ERROR', response_text=f"Error extracting slots: {str(e)}", data={})

        try:
            return await plugin.handle(intent, extracted, raw)
        except Exception as e:
            return CommandResult(success=False, action='PLUGIN_ERROR', response_text=f"Error in plugin {plugin.name}: {str(e)}", data={})

    async def _extract_slots(self, plugin: BaseCommand, intent: str, raw: str) -> dict:
        spec = plugin.get_intent(intent)
        if not spec or not spec.slots:
            return {}
        extracted = await asyncio.to_thread(self.llm_extractor.extract, spec, raw)
        return extracted

    def _get_plugin(self, name: str) -> Optional[BaseCommand]:
        for plugin in self.plugins:
            try:
                if plugin.name == name:
                    return plugin
            except AttributeError:
                continue
        return None


router = CommandRouter(
    intent_classifier=IntentSimilarityModel(),
    llm_extractor=Extractor(model_path="app/ai/models/qwen2.5-1.5b-instruct-q4_k_m.gguf"),
    general_llm=GeneralLLM(model="openai/gpt-oss-120b"),
)